### PR TITLE
OCPCLOUD-2218: Bump CAPG to v1.5.0

### PR DESCRIPTION
**Pull request by damdo**
Bump CAPG provider to v1.5.0

### CODE REVIEW

**Comment by damdo** [comment]
`assets` is expected to fail until https://github.com/openshift/cluster-api-provider-gcp/pull/207 merges.

**Comment by damdo** [comment]
@JoelSpeed  I'm waiting for https://github.com/openshift/cluster-api-provider-gcp/pull/207 to hit the CI payload to test `e2e-gcp-capi-techpreview` properly.

**Comment by JoelSpeed** [comment]
@damdo Checking the [release build](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-capi-operator/142/pull-ci-openshift-cluster-capi-operator-main-e2e-gcp-capi-techpreview/1719321147029327872/artifacts/release/artifacts/release-payload-latest/image-references) for the current job I just kicked off, it appears to be using the correct commit, head from current master.

AFAIK for CI jobs like this we only have to wait for the postsubmit `images` job to complete for the image to be promoted and usable by other CI jobs

**Comment by damdo** [comment]
TIL, thanks.

**Comment by damdo** [comment]
`ci/prow/e2e-gcp-capi-techpreview` fails due to a issue in the upstream release.
This should fix it https://github.com/openshift/cluster-api-provider-gcp/pull/208

**Pull request merged**
