### PR TITLE
Disable azure provider

### PR DESCRIPTION
**Pull request by alexander-demicev**
Disable azure provider since we don't support it now

### CODE REVIEW

**Comment by alexander-demichev** [comment]
I verified that PR works by looking at the must gather of `ci/prow/e2e-azure-techpreview` . CAPZ was not deployed to the cluster.

**Comment by JoelSpeed** [comment]
Aren't we planning to include this in 4.12?

**Comment by alexander-demichev** [comment]
@JoelSpeed I'm not sure what process to follow here. Is it ok to open a PR with a new commit for 4.11 branch? or make a backport of this and then re-enable azure?

**Comment by JoelSpeed** [comment]
> or make a backport of this and then re-enable azure?

The easiest thing is to create a bug in Jira, attach that to this, get this merged, backport using the cherry-pick command, then revert this in main

**Comment by JoelSpeed** [comment]
The alternative option is to go directly to 4.11 but then you need a staff eng to approve

**Comment by lobziik** [comment]
Is this needed?

Should this be merged along with https://github.com/openshift/cluster-capi-operator/pull/75  ?

**Pull request closed without merging**
