### PR TITLE
OCPCLOUD-1870: bump go 1.20, 1.26 deps for k8s/capi/capi providers

### PR DESCRIPTION
**Pull request by damdo**
Done:
- bump go 1.20
- bump k8s dependencies 1.26
- bump CAPI provider deps to versions compatible to 1.26
- bump CAPI core deps to version compatible to 1.26

Todo:
- [x] bump providers-list.yaml and rerun make assets (once provider forks rebase PRs have merged)

As part of this process we are also merging Rebase PRs on the CAPI provider forks.
I will track here E2E tests ran from this branch/PR against the rebase PRs in the various CAPI provider repos forks.

I will track here E2E tests ran from this branch/PR against the rebase PRs in the various CAPI provider repos forks ([details for E2E runs below](https://github.com/openshift/cluster-capi-operator/pull/101#issuecomment-1420478336)).
- [x] [AWS]() - [test-run](https://github.com/openshift/cluster-capi-operator/pull/118#issuecomment-1597176179) ✅  
- [x] [GCP]() - [test-run](https://github.com/openshift/cluster-capi-operator/pull/118#issuecomment-1597176179) ✅ 
- [x] [IBMCloud]() - [test-run](https://github.com/openshift/cluster-api-provider-ibmcloud/pull/56#issuecomment-1609324968) ✅ 
- [x] [Vsphere]() - not testable due to no E2Es yet
- [x] [Azure]() - not testable due to no E2Es yet

### CODE REVIEW

**Comment by damdo** [comment]
Only interested in seeing the required checks to pass, as [all the other relevant jobs passed](https://github.com/openshift/cluster-capi-operator/pull/118#issuecomment-1632731929)
/skip

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
