### PR TITLE
Bug 2084545: Create cluster-capi-operator-secret in right namespace

### PR DESCRIPTION
**Pull request by Fedosin**
The secret should be created in `openshift-cluster-api` namespace.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/approve
/lgtm

**Comment by elmiko** [comment]
/title Bug 2084545: Create cluster-capi-operator-secret in right namespace

**Comment by tkashem** [comment]
/retitle Bug 2084545: Create cluster-capi-operator-secret in right namespace

**Comment by elmiko** [comment]
/retitle Bug 2084545: Create cluster-capi-operator-secret in right namespace

**Pull request merged**
