### PR TITLE
NO-JIRA: Update kustomize in manifests-gen

### PR DESCRIPTION
**Pull request by RadekManak**
Updates Kustomize to latest version. Added note for the next person when they do rebase to keep it up to date. 

I hope that being on the latest version will cause fewer issues in rebases. When any project we run on uses a new feature, the manifest gen breaks. But being ahead on the version affords us a deprecation window.

### CODE REVIEW

**Comment by damdo** [comment]
Skip E2Es as this is a tool change that doesn't affect the payload.
/override e2e-aws-capi-techpreview e2e-aws-ovn e2e-aws-ovn-serial e2e-aws-ovn-techpreview e2e-azure-capi-techpreview e2e-azure-ovn-techpreview e2e-gcp-capi-techpreview e2e-gcp-ovn-techpreview e2e-openstack-capi-techpreview e2e-vsphere-capi-techpreview regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by damdo** [comment]
/override ci/prow/e2e-aws-capi-techpreview ci/prow/e2e-aws-ovn ci/prow/e2e-aws-ovn-serial ci/prow/e2e-aws-ovn-techpreview ci/prow/e2e-azure-capi-techpreview ci/prow/e2e-azure-ovn-techpreview ci/prow/e2e-gcp-capi-techpreview ci/prow/e2e-gcp-ovn-techpreview ci/prow/e2e-openstack-capi-techpreview ci/prow/e2e-vsphere-capi-techpreview ci/prow/regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by damdo** [comment]
Skip E2Es as this is a tool change that doesn't affect the payload.

/override ci/prow/e2e-aws-capi-techpreview ci/prow/e2e-aws-ovn ci/prow/e2e-aws-ovn-serial ci/prow/e2e-aws-ovn-techpreview ci/prow/e2e-azure-capi-techpreview ci/prow/e2e-azure-ovn-techpreview ci/prow/e2e-gcp-capi-techpreview ci/prow/e2e-gcp-ovn-techpreview ci/prow/e2e-openstack-capi-techpreview ci/prow/e2e-vsphere-capi-techpreview ci/prow/regression-clusterinfra-cucushift-rehearse-capi-aws-ipi

**Comment by nrb** [comment]
Thanks for this. I noticed yesterday that the version of kustomize that was used didn't support the `patch` stanza, despite warnings that the older name of `patchStrategicMerge` was deprecated.

**Comment by nrb** [comment]
> Added note for the next person when they do rebase to keep it up to date.

Just to be sure, you mean k8s version bumps, not rebases, right?

**Pull request merged**
