### PR TITLE
Fix outstanding CI failures

### PR DESCRIPTION
**Pull request by mdbooth**
Fixes 2 bugs causing CI failures. As both fixes are required to pass CI this PR also includes https://github.com/openshift/cluster-capi-operator/pull/48

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve
/lgtm

**Comment by mdbooth** [comment]
Rebased to also pull in https://github.com/openshift/cluster-capi-operator/pull/49

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Comment by mdbooth** [comment]
Both e2e-gcp-capi-techpreview and e2e-azure-capi-techpreview failures look like unrelated flakes.

**Comment by mdbooth** [comment]
> are you ok if I override them?

It's your project!

**Pull request merged**
