### PR TITLE
OCPBUGS-22403: Disable CAPI Azure Infrastructure Provider

### PR DESCRIPTION
**Pull request by damdo**
It is causing issues and we don't leverage it yet.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/approve
/lgtm


CC @RadekManak this is being disabled until the migration of the operator work is complete, then we will look at bringing it back in

**Comment by damdo** [comment]
/hold
Until we've verified the azure e2e passes.

**Comment by damdo** [comment]
Looks like Azure TechPreview E2Es are [working again](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-capi-operator/141/pull-ci-openshift-cluster-capi-operator-main-e2e-azure-ovn-techpreview/1717514435079180288) thanks to this change.

```
[~] $ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-capi-operator/141/pull-ci-openshift-cluster-capi-operator-main-e2e-azure-ovn-techpreview/1717514435079180288/artifacts/e2e-azure-ovn-techpreview/gather-extra/artifacts/pods/openshift-cluster-api_cluster-capi-operator-7cfcc44d74-6spzl_cluster-capi-operator.log | grep "skipping"

I1026 12:54:35.596625       1 main.go:271] Platform not supported, skipping infra cluster controller setup
```

**Comment by damdo** [comment]
Happy with the result.
/unhold

**Pull request merged**
