### PR TITLE
OCPBUGS-10809: feat: add workload annotations

### PR DESCRIPTION
**Pull request by eggfoobar**
added logic to merge in workload annotations to deployments

### CODE REVIEW

**Comment by eggfoobar** [comment]
Verified that for the GCP deployments. The below deployments have the correct annotations added.

- `capi-operator-controller-manager`
- `capi-controller-manager`
- `capg-controller-manager`

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-capi-operator/107/pull-ci-openshift-cluster-capi-operator-main-e2e-gcp-ovn-techpreview/1640361555725914112/artifacts/e2e-gcp-ovn-techpreview/gather-extra/artifacts/deployments.json

**Comment by damdo** [comment]
@eggfoobar do we need backporting for this?

**Comment by eggfoobar** [comment]
> @eggfoobar do we need backporting for this?

Yeah, luckily we just need to bring it back to 4.13

**Pull request merged**
