### PR TITLE
Refactor import-assets

### PR DESCRIPTION
**Pull request by alexander-demichev**
Instead of iterating through objects multiple times, we can do it in one go.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
i like how you've brought the object processing together, i don't have any strong thoughts about changes
/lgtm

**Comment by lobziik** [comment]
tests are reporting about bunch of alerts and crushes from cluster-capi-operator, @alexander-demichev can you take a look please, it might be connected with this changes

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Pull request merged**
